// flow-typed signature: 22e8efcaf40c9259fceba944d7230768
// flow-typed version: <<STUB>>/express-force-ssl_v^0.3.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-force-ssl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-force-ssl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-force-ssl/examples/example' {
  declare module.exports: any;
}

declare module 'express-force-ssl/test/http' {
  declare module.exports: any;
}

declare module 'express-force-ssl/test/https-disable-301s' {
  declare module.exports: any;
}

declare module 'express-force-ssl/test/https' {
  declare module.exports: any;
}

declare module 'express-force-ssl/test/server/index' {
  declare module.exports: any;
}

declare module 'express-force-ssl/test/variable-overide' {
  declare module.exports: any;
}

declare module 'express-force-ssl/test/x-forwarded-proto-trusted' {
  declare module.exports: any;
}

declare module 'express-force-ssl/test/x-forwarded-proto' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-force-ssl/examples/example.js' {
  declare module.exports: $Exports<'express-force-ssl/examples/example'>;
}
declare module 'express-force-ssl/index' {
  declare module.exports: $Exports<'express-force-ssl'>;
}
declare module 'express-force-ssl/index.js' {
  declare module.exports: $Exports<'express-force-ssl'>;
}
declare module 'express-force-ssl/test/http.js' {
  declare module.exports: $Exports<'express-force-ssl/test/http'>;
}
declare module 'express-force-ssl/test/https-disable-301s.js' {
  declare module.exports: $Exports<'express-force-ssl/test/https-disable-301s'>;
}
declare module 'express-force-ssl/test/https.js' {
  declare module.exports: $Exports<'express-force-ssl/test/https'>;
}
declare module 'express-force-ssl/test/server/index.js' {
  declare module.exports: $Exports<'express-force-ssl/test/server/index'>;
}
declare module 'express-force-ssl/test/variable-overide.js' {
  declare module.exports: $Exports<'express-force-ssl/test/variable-overide'>;
}
declare module 'express-force-ssl/test/x-forwarded-proto-trusted.js' {
  declare module.exports: $Exports<'express-force-ssl/test/x-forwarded-proto-trusted'>;
}
declare module 'express-force-ssl/test/x-forwarded-proto.js' {
  declare module.exports: $Exports<'express-force-ssl/test/x-forwarded-proto'>;
}
