// flow-typed signature: 17d010fdd55d15ef2b2ce2302a860a98
// flow-typed version: <<STUB>>/redux-pack_v^0.1.5/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-pack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-pack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-pack/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-pack/lib/handle' {
  declare module.exports: any;
}

declare module 'redux-pack/lib/index' {
  declare module.exports: any;
}

declare module 'redux-pack/lib/middleware' {
  declare module.exports: any;
}

declare module 'redux-pack/src/constants' {
  declare module.exports: any;
}

declare module 'redux-pack/src/handle' {
  declare module.exports: any;
}

declare module 'redux-pack/src/index' {
  declare module.exports: any;
}

declare module 'redux-pack/src/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-pack/lib/constants.js' {
  declare module.exports: $Exports<'redux-pack/lib/constants'>;
}
declare module 'redux-pack/lib/handle.js' {
  declare module.exports: $Exports<'redux-pack/lib/handle'>;
}
declare module 'redux-pack/lib/index.js' {
  declare module.exports: $Exports<'redux-pack/lib/index'>;
}
declare module 'redux-pack/lib/middleware.js' {
  declare module.exports: $Exports<'redux-pack/lib/middleware'>;
}
declare module 'redux-pack/src/constants.js' {
  declare module.exports: $Exports<'redux-pack/src/constants'>;
}
declare module 'redux-pack/src/handle.js' {
  declare module.exports: $Exports<'redux-pack/src/handle'>;
}
declare module 'redux-pack/src/index.js' {
  declare module.exports: $Exports<'redux-pack/src/index'>;
}
declare module 'redux-pack/src/middleware.js' {
  declare module.exports: $Exports<'redux-pack/src/middleware'>;
}
